baseURL = "https://www.allysonoliveira.com.br"
languageCode = "en-us"
enableInlineShortcodes = true
title = "Allyson Oliveira"
theme = "soho"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-162896323-1"
disqusShortname = "allyshow"

[params]
description = "Arquiteto de Soluções na AWS | IA Generativa & Cloud"
profilePicture="/img/profile.png"
highlightjs = true
highlightjsstyle = "github"

# sidebar, copyright & license
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/allysonoliveira"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/asoliveira"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Fale comigo!"
    identifier = "Sobre Mim"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Projetos"
    identifier = "Projetos"
    weight = 200
    url = "/projetos/"